# Generated by Django 4.2 on 2026-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expires_at', models.DateTimeField()),
                ('max_usages', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(blank=True, related_name='promo_codes', to='products.category')),
            ],
        ),
    ]
